### ISSUE TITLE
Unable to import package

### ISSUE THREAD

**Issue by KnowingXR** [Boxei/Box#1]
When importing like a normal package it provides and error saying a module attribute doesn't exist or module not found.

Tasks:

- [x] Allow imports
- [x] Make the import process more simpler
- [x] Fix the problem

**Comment by KnowingXR** [comment]
Traceback (most recent call last):
  File "c:\Users\Knowi\Documents\VSC\Box\venv\main.py", line 1, in <module>
    from box import frame
  File "C:\Users\Knowi\Documents\VSC\Box\venv\Lib\site-packages\box\__init__.py", line 1, in <module>
    from frame import *
ModuleNotFoundError: No module named 'frame'

Given error code

**Comment by KnowingXR** [comment]
Problem was in __init__.py and how it was being called.
